
spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-log.yaml


logging:
  level:
    com.example.demo: DEBUG

scheduler:
  balance-increase:
    interval: 30000
