spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/bank-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-log.yaml

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    com.example.demo: DEBUG

scheduler:
  balance-increase:
    interval: 30000
