services:

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      internal:

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 5s
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: demo-redis
    ports:
      - "6379:6379"

networks:
  internal:
    driver: bridge


